version: "3.2"
services:
  metaclient:
    image: ayias-metaclient-main
    container_name: ayias-metaclient
    network_mode: host
    ports:
      - 19504:19504
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
    deploy:
      mode: replicated
      replicas: 4