version: "3.2"
services:
  metaserver:
    container_name: ayias-metaserver
    build:
      context: ../../dist/apps/metaserver
      dockerfile: ../../../apps/metaserver/Dockerfile
    network_mode: host
    command: node main.js --max-old-space-size=8192
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1

  metaclient: 
    container_name: ayias-metaclient
    build:
      context: ../../dist/apps/metaclient
      dockerfile: ../../../apps/metaclient/Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
    deploy:
      replicas: 1